### ISSUE TITLE
Where is configuration of this project?

### ISSUE THREAD

**Issue by kuldeepgade** [Chalandi/OSEK#2]
@Chalandi : There are structures "Ocb_t" , "Alarm_t","Resource_t","Tcb_t" & "Isr_t".
Could you please let me know, where these structure members are initialized?

**Comment by Chalandi** [comment]
@kuldeepgade : They are hidden for the user, the initialization is done by using x-marco (take a look to OsGenMac.h)

**Comment by kuldeepgade** [comment]
> @kuldeepgade : They are hidden for the user, the initialization is done by using x-marco (take a look to OsGenMac.h)

Thanks.
