### ISSUE TITLE
This implementation does not include time-slices

### ISSUE THREAD

**Issue by kuldeepgade** [Chalandi/OSEK#3]
@Chalandi :Time slices like 1ms, 5ms, 10ms etc.are not available in the code. Is there any specific reason?
Is it possible to add time-slices to the existing code?
Your inputs will be helpful.

**Comment by Chalandi** [comment]
@kuldeepgade:  It's actually supported by using Alarms, you can define a cyclic or one shoot alarms (timers) in osGenCfg.h:

Example :

  OS_ALARM_BEGIN
    OS_ALARM_DEF(ALARM_BLUE_LED ,ALARM_SET_EVENT ,EVT_BLINK_BLUE_LED ,Task1 ,0)
  OS_ALARM_END

This will define an alarm named "ALARM_BLUE_LED" which set an event named "EVT_BLINK_BLUE_LED" when the timeout is occurred to a task named "Task1".

in your application you can start or stop the alarm using the following APIs :
start:  OS_SetRelAlarm or OS_SetAbsAlarm
stop:  OS_CancelAlarm

**Comment by kuldeepgade** [comment]
thanks. this information is helpful.
