### ISSUE TITLE
Time-slices implementation

### ISSUE THREAD

**Issue by kuldeepgade** [Chalandi/OSEK#6]
@Chalandi: I have successfully executed ONE SHOT alarms. But, how cyclic execution can be done.
Can you give any example for execution of 5ms time-slice.
This time slice shall execute every 5ms.

Thanks.

**Comment by Chalandi** [comment]
@kuldeepgade:
OsStatusType OS_SetRelAlarm(OsAlarmType AlarmID, OsTickType increment, OsTickType cycle)

by setting the parameter cycle to 5ms you create a cyclic alarm.
when you set cycle to 0 you create a one shot alarm.

Example:
If your system tick is 1ms then this function call will create a cyclic alarm 
OS_SetRelAlarm(Your_Alarm_ID,  0, 5);

**Comment by kuldeepgade** [comment]
It is working.
Thanks
