### ISSUE TITLE
Preempted Task does not resume from last step

### ISSUE THREAD

**Issue by kuldeepgade** [Chalandi/OSEK#7]
@Chalandi  : If 5ms task is in execution, at certain step, 1ms Tick arrived. Control shall passes to 1ms.
But, while coming back to 5ms, it shall resume execuion from the point it left.
This is not happening.
Please suggets your inputs.

Thanks

**Comment by Chalandi** [comment]
@kuldeepgade : Can you explain more what you mean by "This is not happening" ?

When you have in your application another higher prio task than the 5ms task which became ready just after the execution of the systick interrupt, the OS will switch the context to this higher prio task instead of coming back to the 5ms (after the systick ISR execution).

Is that the case in your application ?

**Comment by kuldeepgade** [comment]
![16347227869271579428876713873786](https://user-images.githubusercontent.com/73546526/138069279-02a607f0-145a-4280-9ae5-b5eca2413a12.jpg)

@Chalandi : Task execution flow is explained in this diagram

**Comment by Chalandi** [comment]
@kuldeepgade : Could you share your OS Config file ?

**Comment by kuldeepgade** [comment]
@Chalandi :
Configuration file will be in different format.
But, I can share you details like priority.
Idle_Task- 5,
Init_Task - 4,
1ms Task- 3,
5ms Task - 2
All tasks are EXTENDED, SUSPENDED, FULL PREEMPTIVE.

Only INIT Task is AUTOSTART task.

**Comment by Chalandi** [comment]
What about the stack sizes ?  Do you terminate the task TASK_5ms for any reason in your code ?

**Comment by kuldeepgade** [comment]
1. Stack Sizes assigned for each task = 64 Words = 256 bytes. [How to optimize this? as it consumes much RAM]
2. I do terminate each Task.

Example: 
TASK(T_5MS)
{
  for (; ;)
  {
    function code;
    TerminateTask();
  }
}

TASK(T_1MS)
{
  for (; ;)
  {
    function code;
    TerminateTask();
  }
}

**Comment by kuldeepgade** [comment]
@Chalandi : it seems like context saving is successful but  context reloading / restoring is not happening for preempted task.
Each time it create new context and start execution from beginning of task.

**Comment by kuldeepgade** [comment]
@Chalandi : can you suggest something, why control doesn't return after POP instruction execution in both the handlers.
POP("");
BX LR;

**Comment by Chalandi** [comment]
@kuldeepgade : Could you please share more details about the issue ? maybe share a piece of code and a brief description of the issue in order to help you fixing it

**Comment by kuldeepgade** [comment]
@Chalandi :  in OsAsm.c, Os_Dispatcher, Line-40,
control never returns to this line after execution of POP instruction on line-39.
Similarly, for Os_Cat2IsrWrapper function,
Control never returns to Line-105, after execution of POP instruction on Line-103.
![20211215_202700](https://user-images.githubusercontent.com/73546526/146210460-3c61f713-4a00-41a5-93e3-c0ee1b066ec9.jpg)
![20211215_202626](https://user-images.githubusercontent.com/73546526/146210600-a1d25c51-edde-4a70-90bd-c6813ef8687f.jpg)

**Comment by Chalandi** [comment]
@kuldeepgade : how did you checked that the last two instructions are never executed ? 
The instruction POP here doesn't update the PC register so the CPU must continue executing the last two instructions (cpsie and bx) before exit the exception handler :

![image](https://user-images.githubusercontent.com/7204744/146330409-d2fbe9ae-2609-4e74-bea4-2f0f0f082a66.png)

Are you running the OS on Cortex-M3 CPU ?  This OS version was made for Cortex-M3 without FPU, so if you're running it on any other Cortex-M with FPU enabled you will get some lazy stacking issues as this OS doesn't support the FPU.

**Comment by kuldeepgade** [comment]
@Chalandi : I checked with debugger breakpoints.
Thanks for your inputs.
